# Generated by Django 2.1.7 on 2019-03-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BinaryTreeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('level', models.IntegerField()),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_node_left', to='binary_tree.BinaryTreeNode')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_node_parent', to='binary_tree.BinaryTreeNode')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_node_right', to='binary_tree.BinaryTreeNode')),
            ],
        ),
        migrations.AddField(
            model_name='binarytree',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binary_tree.BinaryTreeNode'),
        ),
    ]
