# Generated by Django 2.1.7 on 2019-03-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binary_tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarytree',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='binarytree',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='binarytreenode',
            name='left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_node_left', to='binary_tree.BinaryTreeNode'),
        ),
        migrations.AlterField(
            model_name='binarytreenode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_node_parent', to='binary_tree.BinaryTreeNode'),
        ),
        migrations.AlterField(
            model_name='binarytreenode',
            name='right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_node_right', to='binary_tree.BinaryTreeNode'),
        ),
    ]
